pipeline {
  agent any

  options {
    buildDiscarder(
      logRotator(
        numToKeepStr: '3',
        daysToKeepStr: '5'
      )
    )
  }

  environment {
    REPO_NAME   = "Bedrock-agentcore-new"
    AWS_REGION  = "us-east-1"
    AWS_PROFILE = "jenkins"
    ACCOUNT_ID  = "897675553288"

    ECR_REPO    = "test/astrolimeagent"
    IMAGE_TAG   = "1.${BUILD_NUMBER}"
    IMAGE_URI   = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"

    RUNTIME_ID  = "astroLime_Agent-RSlT6A3waq"
    RUNTIME_ROLE_ARN = "arn:aws:iam::897675553288:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-7171c955a3"
    NETWORK_MODE = "PUBLIC"

  }

  stages {

    stage('Checkout') {
      steps {
        dir("${WORKSPACE}/${REPO_NAME}") {
          git branch: 'main',
              credentialsId: "Dhairya335-bedrock-agentcore",
              url: "https://github.com/Dhairya335/${REPO_NAME}"
        }
      }
    }

//    stage('Validate AWS Identity') {
 //     steps {
 //       dir("${WORKSPACE}/${REPO_NAME}") {
 //         sh '''
 //           aws sts get-caller-identity --profile ${AWS_PROFILE}
 //         '''
 //       }
 //     }
 //   }

    stage('Verify ECR Repository Exists') {
      steps {
        dir("${WORKSPACE}/${REPO_NAME}") {
          sh '''
            aws ecr describe-repositories \
              --repository-names ${ECR_REPO} \
              --region ${AWS_REGION} \
              --profile ${AWS_PROFILE}
          '''
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir("${WORKSPACE}/${REPO_NAME}") {
          sh '''
            podman build --platform linux/arm64 -t astrolimeagent:${IMAGE_TAG} .
          '''
        }
      }
    }

    stage('Login to ECR') {
      steps {
        sh '''
          aws ecr get-login-password \
            --region ${AWS_REGION} \
            --profile ${AWS_PROFILE} \
          | podman login \
            --username AWS \
            --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
        '''
      }
    }

    stage('Tag Image and push to ECR') {
      steps {
        sh '''
          podman tag astrolimeagent:${IMAGE_TAG} ${IMAGE_URI}
          podman push ${IMAGE_URI}
        '''
      }
    }

    stage('Deploy to AgentCore') {
      steps {
      	sh '''
          aws bedrock-agentcore-control update-agent-runtime \
          --agent-runtime-id ${RUNTIME_ID} \
          --agent-runtime-artifact containerConfiguration={containerUri=${IMAGE_URI}} \
          --role-arn ${RUNTIME_ROLE_ARN} \
          --network-configuration networkMode=${NETWORK_MODE} \
          --region ${AWS_REGION} \
          --profile ${AWS_PROFILE}
        '''
      }
    }
  }
}
